trigger:
- master

pool:
  vmImage: 'windows-latest'  # <-- Change this if needed

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    ng build --configuration production
  displayName: 'npm install and build'

